StatTracker/config/routes.rb
StatTracker::Application.routes.draw do
  
  
  match 'index' => 'home#index', :as => 'home#index'
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  
  match 'compare' => 'home#compare', :as => 'home#compare'
  match 'franchise_compare' => 'home#franchise_compare'
  match 'home/google' => 'search#google_images', :as => 'home#google'
  match 'batting_leaderboards' => 'home#batting_leaderboard'
  match 'pitching_leaderboards' => 'home#pitching_leaderboard'
  match 'fielding_leaderboards' => 'home#fielding_leaderboard'
  match 'batting_leaders' => 'home#batting_leaders'
  match 'pitching_leaders' => 'home#pitching_leaders'
  match 'fielding_leaders' => 'home#fielding_leaders'
  match 'years_players' => 'home#years_players'
  match 'compare_players' => 'home#compare_players'
  
  match 'years_franchises' => 'home#years_franchises'
  match 'compare_franchises' => 'home#compare_franchises'

  match 'players/letter/' => 'players#by_letter', :as => :players_by_letter
  match 'players/letter/:letter' => 'players#letter', :as => :players_letter

  match 'players/position/' => 'players#by_position', :as => :players_by_position
  match 'players/position/:position' => 'players#position', :as => :players_position
  
  get 'home/autocomplete_player_name'
  get 'home/autocomplete_franchise_name'
  get 'players/autocomplete_player_name'
  get 'franchises/autocomplete_franchise_name'

  resources :teams

  resources :players

  resources :pitching_stats

  resources :pitching_post_stats

  resources :franchises

  resources :leagues

  resources :fielding_stats

  resources :fielding_post_stats

  resources :divisions

  resources :batting_stats

  resources :batting_post_stats
  
  match 'leaders/season/batting/:stat' => 'batting_stats#single_season'
  match 'leaders/season/batting_post/:stat' => 'batting_post_stats#single_season'
  match 'leaders/season/pitching/:stat' => 'pitching_stats#single_season'
  match 'leaders/season/pitching_post/:stat' => 'pitching_post_stats#single_season'
  match 'leaders/season/fielding/:stat' => 'fielding_stats#single_season'
  match 'leaders/season/fielding_post/:stat' => 'fielding_post_stats#single_season'
  
  match 'leaders/career/batting/:stat' => 'batting_stats#career'
  match 'leaders/career/batting_post/:stat' => 'batting_post_stats#career'
  match 'leaders/career/pitching/:stat' => 'pitching_stats#career'
  match 'leaders/career/pitching_post/:stat' => 'pitching_post_stats#career'
  match 'leaders/career/fielding/:stat' => 'fielding_stats#career'
  match 'leaders/career/fielding_post/:stat' => 'fielding_post_stats#career'

  match 'leaders/active/batting/:stat' => 'batting_stats#active'
  match 'leaders/active/batting_post/:stat' => 'batting_post_stats#active'
  match 'leaders/active/pitching/:stat' => 'pitching_stats#active'
  match 'leaders/active/pitching_post/:stat' => 'pitching_post_stats#active'
  match 'leaders/active/fielding/:stat' => 'fielding_stats#active'
  match 'leaders/active/fielding_post/:stat' => 'fielding_post_stats#active'
  
  match 'compare/season/batting/*comp' => 'batting_stats#season_compare'
  match 'compare/career/batting/*comp' => 'batting_stats#career_compare'
  match 'compare/multi/batting/*comp' => 'batting_stats#multi_compare'
  match 'compare/season/pitching/*comp' => 'pitching_stats#season_compare'
  match 'compare/career/pitching/*comp' => 'pitching_stats#career_compare'
  match 'compare/multi/pitching/*comp' => 'pitching_stats#multi_compare'

  match 'franchise_compare/season/*comp' => 'teams#season_compare'
  match 'franchise_compare/career/*comp' => 'teams#career_compare'
  match 'franchise_compare/multi/*comp' => 'teams#multi_compare'
  
  match 'seasonfinder/batting' => 'batting_stats#season_finder'
  match 'seasonfinder/batting/results' => 'batting_stats#find_seasons'
  match 'seasonfinder/pitching' => 'pitching_stats#season_finder'
  match 'seasonfinder/pitching/results' => 'pitching_stats#find_seasons'
  match 'seasonfinder/fielding' => 'fielding_stats#season_finder'
  match 'seasonfinder/fielding/results' => 'fielding_stats#find_seasons'
  
  match 'change_career_chart_batting' => 'batting_stats#change_career_chart'
  match 'change_career_table_batting' => 'batting_stats#change_career_table'
  match 'change_career_chart_pitching' => 'pitching_stats#change_career_chart'
  match 'change_career_table_pitching' => 'pitching_stats#change_career_table'
  match 'change_career_chart_team' => 'teams#change_career_chart'
  match 'change_career_table_team' => 'teams#change_career_table'
  
  match 'change_multi_chart_batting' => 'batting_stats#change_multi_chart'
  match 'change_multi_table_batting' => 'batting_stats#change_multi_table'
  match 'change_multi_chart_pitching' => 'pitching_stats#change_multi_chart'
  match 'change_multi_table_pitching' => 'pitching_stats#change_multi_table'
  match 'change_multi_chart_team' => 'teams#change_multi_chart'
  match 'change_multi_table_team' => 'teams#change_multi_table'
  
  match 'search' => 'home#search', :as => :search

  match 'team_search' => 'franchises#team_search', :as => :team_search
  match 'player_search' => 'players#player_search', :as => :player_search

   root :to => "home#index"

end

StatTracker/app/controllers/pitching_stats_controller.rb
class PitchingStatsController < ApplicationController
  def index
    @pitching_stats = PitchingStat.all
  end

  def show
    @pitching_stat = PitchingStat.find(params[:id])
  end
  
	def single_season
		@pitching_stats = PitchingStat.single_season_sort(params[:stat])
		@table = GoogleVisualr::Table.new
		@table.add_column('string' , 'Name')
		@table.add_column('string' , 'Throws')
		@table.add_column('string' , 'Team')
		@table.add_column('string' , 'Year')
		if params[:stat] == 'era'
			@table.add_column('string' , params[:stat].upcase)
		else @table.add_column('string' , params[:stat].titleize)
		end
		@table.add_rows(50)
		@pitching_stats.each { |b|
			i = @pitching_stats.index(b)
			@table.set_cell(i, 0, "<a href='/players/#{b.player.id}'>#{b.player.name}</a>")
			if !b.player.throws.nil?
				@table.set_cell(i, 1, b.player.throws)
			else @table.set_cell(i, 1, 'N/A')
			end
			@table.set_cell(i, 2, "<a href='/teams/#{b.team.id}'>#{b.team.name}</a>")
			@table.set_cell(i, 3, "#{b.year}")
			@table.set_cell(i, 4, "#{b.send(params[:stat])}")
		}
		
		options = { :width => 600, :showRowNumber => true, :allowHtml=>true  }
		options.each_pair do | key, value |
			@table.send "#{key}=", value
		end	
	end
	
	def career
		@pitching_stats = PitchingStat.career_sort(params[:stat])
		@table = GoogleVisualr::Table.new
		@table.add_column('string' , 'Name')
		@table.add_column('string' , 'Throws')
		if params[:stat] == 'era'
			@table.add_column('string' , params[:stat].upcase)
		else @table.add_column('string' , params[:stat].titleize)
		end
		@table.add_rows(50)
		i = 0
			if PitchingStat.accessible_attributes.include?(params[:stat])
				@pitching_stats.each { |k, v|
					@table.set_cell(i, 0, "<a href='/players/#{k.id}'>#{k.name}</a>")
					if !k.throws.nil?
						@table.set_cell(i, 1, k.throws)
					else @table.set_cell(i, 1, 'N/A')
					end
					@table.set_cell(i, 2, "#{v}")
					i += 1
				}
			else 
				@pitching_stats.each { |b|
					@table.set_cell(i, 0, "<a href='/players/#{b.id}'>#{b.name}</a>")
					if !b.throws.nil?
						@table.set_cell(i, 1, b.throws)
					else @table.set_cell(i, 1, 'N/A')
					end
					@table.set_cell(i, 2, "#{b.send("career_" + params[:stat])}")
					i += 1
				}
			end
		options = { :width => 600, :showRowNumber => true, :allowHtml=>true  }
		options.each_pair do | key, value |
			@table.send "#{key}=", value
		end
	end
	
	def active
		@pitching_stats = PitchingStat.active_sort(params[:stat])
		@table = GoogleVisualr::Table.new
		@table.add_column('string' , 'Name')
		@table.add_column('string' , 'Throws')
		if params[:stat] == 'era'
			@table.add_column('string' , params[:stat].upcase)
		else @table.add_column('string' , params[:stat].titleize)
		end
		@table.add_rows(50)
		i = 0
			if PitchingStat.accessible_attributes.include?(params[:stat])
				@pitching_stats.each { |k, v|
					@table.set_cell(i, 0, "<a href='/players/#{k.id}'>#{k.name}</a>")
					if !k.throws.nil?
						@table.set_cell(i, 1, k.throws)
					else @table.set_cell(i, 1, 'N/A')
					end
					@table.set_cell(i, 2, "#{v}")
					i += 1
				}
			else 
				@pitching_stats.each { |b|
					@table.set_cell(i, 0, "<a href='/players/#{b.id}'>#{b.name}</a>")
					if !b.throws.nil?
						@table.set_cell(i, 1, b.throws)
					else @table.set_cell(i, 1, 'N/A')
					end
					@table.set_cell(i, 2, "#{b.send("career_" + params[:stat])}")
					i += 1
				}
			end	
		options = { :width => 600, :showRowNumber => true, :allowHtml=>true  }
		options.each_pair do | key, value |
			@table.send "#{key}=", value
		end
	end
	
	def season_compare
		@pitchers = PitchingStat.season_compare(params[:comp])
		if @pitchers.empty?	
			flash[:notice] = "One or more of the players you have chosen do not have pitching statistics available. Please select different players."
			redirect_to :back
		else
			@table = GoogleVisualr::Table.new
			@table.add_column('string' , 'Name')
			@table.add_column('string' , 'Bats')
			@table.add_column('string' , 'Year')
			@table.add_column('string' , 'Age')
			@table.add_column('string' , 'Team')
			@table.add_column('string' , 'League')
			@table.add_column('number' , 'W')
			@table.add_column('number' , 'L')
			@table.add_column('string' , 'WL%')
			@table.add_column('string' , 'ERA')
			@table.add_column('number' , 'G')
			@table.add_column('number' , 'GS')
			@table.add_column('number' , 'CG')
			@table.add_column('number' , 'SHO')
			@table.add_column('number' , 'SV')
			@table.add_column('string' , 'IP')
			@table.add_column('number' , 'H')
			@table.add_column('number' , 'R')
			@table.add_column('number' , 'ER')
			@table.add_column('number' , 'HR')
			@table.add_column('number', 'BB')
			@table.add_column('number' , 'IBB')
			@table.add_column('number' , 'K')
			@table.add_column('number' , 'HBP')
			@table.add_column('number' , 'BK')
			@table.add_column('number' , 'WP')
			@table.add_column('number' , 'BF')
			@table.add_column('string' , 'WHIP')
			@table.add_column('string' , 'H/9')
			@table.add_column('string' , 'HR/9')
			@table.add_column('string' , 'BB/9')
			@table.add_column('string' , 'K/9')
			@table.add_column('string' , 'K/BB')
			@table.add_rows(@pitchers.size)
			i = 0
			@pitchers.each {|b|
				@table.set_cell(i, 0, "<a href='/players/#{b[0].player_id}'>#{b[0].player.name}</a>")
				if !b[0].player.bats.nil?
					@table.set_cell(i, 1, b[0].player.bats.to_s)
				else @table.set_cell(i, 1, 'N/A')
				end
				  wins="\"Wins \""
				  losses="\"Losses\""
				  games="\"Games\""
				  started="\"Games Started\""
				  finished="\"Games Finished\""
				  complete="\"Complete Games\""
				  shutouts="\"Shutouts\""
				  saves="\"Saves\""
				  hits="\"Hits Allowed\""
				  runs="\"Runs Alowed\""
				  earned="\"Earned Runs\""
				  home="\"Home Runs Allowed\""
				  walks="\"Walks\""
				  intentional="\"Intentional Walks\""
				  strikes="\"Strikeouts\""
				  hitbypitch="\"Hit by Pitch\""
				  balks="\"Balks\""
				  wild="\"Wild Pitches\""
				  batters="\"Batters Faced\""
				@table.set_cell(i, 2, b[0].team.year.to_s)
				@table.set_cell(i, 3, b[0].player.age(b[0].team.year).to_s)
				@table.set_cell(i, 4, "<a href='/teams/#{b[0].team.id}'>#{b[0].team.name}</a>")
				@table.set_cell(i, 5, b[0].team.division.league.abbrev.to_s)
				@table.set_cell(i, 6, b[0].wins, "<span title=#{wins}>#{b[0].wins.to_s}</span>")
				@table.set_cell(i, 7, b[0].losses, "<span title=#{losses}>#{b[0].losses.to_s}</span>")
				@table.set_cell(i, 8, "<span title='Win Loss Percentage'>#{b[0].win_loss_percentage.to_s}</span>" )
				@table.set_cell(i, 9, "<span title='ERA'>#{b[0].era.to_s}</span>" )
				@table.set_cell(i, 10, b[0].games, "<span title=#{games}>#{b[0].games.to_s}</span>" )
				@table.set_cell(i, 11, b[0].games_started, "<span title=#{started}>#{b[0].games_started.to_s}</span>" )
				@table.set_cell(i, 12, b[0].complete_games, "<span title=#{complete}>#{b[0].complete_games.to_s}</span>" )
				@table.set_cell(i, 13, b[0].shutouts, "<span title=#{shutouts}>#{b[0].shutouts.to_s}</span>")
				@table.set_cell(i, 14, b[0].saves, "<span title=#{saves}>#{b[0].saves.to_s}</span>" )
				@table.set_cell(i, 15, "<span title='Innings Pitched'>#{b[0].innings_pitched_display.to_s}</span>" )
				@table.set_cell(i, 16, b[0].hits, "<span title=#{hits}>#{b[0].hits.to_s}</span>" )
				@table.set_cell(i, 17, b[0].runs, "<span title=#{runs}>#{b[0].runs.to_s}</span>" )
				@table.set_cell(i, 18, b[0].earned_runs, "<span title=#{earned}>#{b[0].earned_runs.to_s}</span>")
				@table.set_cell(i, 19, b[0].home_runs, "<span title=#{home}>#{b[0].home_runs.to_s}</span>")
				@table.set_cell(i, 20, b[0].walks, "<span title=#{walks}>#{b[0].walks.to_s}</span>")
				@table.set_cell(i, 21, b[0].intentional_walks, "<span title=#{intentional}>#{b[0].intentional_walks.to_s}</span>" )
				@table.set_cell(i, 22, b[0].strikeouts, "<span title=#{strikes}>#{b[0].strikeouts.to_s}</span>")
				@table.set_cell(i, 23, b[0].hit_by_pitch, "<span title=#{hitbypitch}>#{b[0].hit_by_pitch.to_s}</span>" )
				@table.set_cell(i, 24, b[0].balks, "<span title=#{balks}>#{b[0].balks.to_s}</span>" )
				@table.set_cell(i, 25, b[0].wild_pitches, "<span title=#{wild}>#{b[0].wild_pitches.to_s}</span>")
				@table.set_cell(i, 26, b[0].batters_faced,"<span title=#{batters}>#{b[0].batters_faced.to_s}</span>" )
				@table.set_cell(i, 27, "<span title='Walks and Hits per Innings Pitched'>#{b[0].walks_and_hits_innings_pitched.to_s}</span>" )
				@table.set_cell(i, 28, "<span title='Hits per 9 Innings'>#{b[0].hits_per_9_innings.to_s}</span>" )
				@table.set_cell(i, 29, "<span title='Home Runs per 9 Innings'>#{b[0].home_runs_per_9_innings.to_s}</span>" )
				@table.set_cell(i, 30, "<span title='Walks per 9 Innings'>#{b[0].walks_per_9_innings.to_s}</span>" )
				@table.set_cell(i, 31, "<span title='Strikeouts per 9 Innings'>#{b[0].strikeouts_per_9_innings.to_s}</span>" )
				@table.set_cell(i, 32, "<span title='Strikeouts per Walk'>#{b[0].strikeouts_per_walk.to_s}</span>" )
				i += 1
			}
			
			options = { :width => '100%', :allowHtml=>true }
			options.each_pair do | key, value |
				@table.send "#{key}=", value
			end
			
			  wins="\"Wins \""
				  losses="\"Losses\""
				  saves="\"Saves\""
				  strikes="\"Strikeouts\""
			@chart = GoogleVisualr::Table.new
			@chart.add_column('string' , 'Name')
			@chart.add_column('string' , 'Bats')
			@chart.add_column('string' , 'Year')
			@chart.add_column('string' , 'Age')
			@chart.add_column('string' , 'Team')
			@chart.add_column('string' , 'League')
			@chart.add_column('number' , 'W')
			@chart.add_column('number' , 'L')
			@chart.add_column('string' , 'ERA')
			@chart.add_column('number' , 'SV')
			@chart.add_column('string' , 'IP')
			@chart.add_column('number' , 'K')
			@chart.add_column('string' , 'WHIP')
			@chart.add_rows(@pitchers.size)
			i = 0
			@pitchers.each {|b|
				@chart.set_cell(i, 0, "<a href='/players/#{b[0].player_id}'>#{b[0].player.name}</a>")
				if !b[0].player.bats.nil?

StatTracker/app/helpers/pitching_stats_helper.rb
module PitchingStatsHelper
end

StatTracker/app/views/pitching_stats/_chart.html.erb
<div id = 'chart'></div>
<%= raw @chart.render('chart') %>

StatTracker/app/views/pitching_stats/_chart.js.erb
<table class = 'chart'>
	<tr>
		<td class = 'chart'>
			<div id = 'chart1'></div>
			<%= raw @chart.render('chart1') %>
		</td>
		<td class = 'chart'>
			<div id = 'chart2'></div>
			<%= raw @chart2.render('chart2') %>
		</td>
	</tr>
</table>

StatTracker/app/views/pitching_stats/career_compare.html.erb
<% title "Career Pitching Comparison" %>

	<div id = 'table_place'>
		<%= render :partial => 'table'  %> 
	</div>
	
	<br/>
	
	<div id = "table_checkbox">
		<span><p>Check which statistics you want to view in the table</p></span>
		<%= form_tag change_career_table_pitching_path(:players => @players), :remote => true, :id => "change_table"   do %>
			<span title="Wins"><%= check_box_tag 'stat[]', 'wins', true %>W</span>&nbsp;
			<span title="Losses"><%= check_box_tag 'stat[]', 'losses', true %>L</span>&nbsp;
			<span title="Games"><%= check_box_tag 'stat[]', 'games', false %>G</span>&nbsp;
			<span title="Games Started"><%= check_box_tag 'stat[]', 'games_started', false %>GS</span>&nbsp;
			<span title="Complete Games"><%= check_box_tag 'stat[]', 'complete_games', false %>CG</span>&nbsp;
			<span title="Shutouts"><%= check_box_tag 'stat[]', 'shutouts', false %>SO</span>&nbsp;
			<span title="Saves"><%= check_box_tag 'stat[]', 'saves', true %>SV</span>&nbsp;
			<span title="Hits"><%= check_box_tag 'stat[]', 'hits', false %>H</span>&nbsp;
			<span title="Runs"><%= check_box_tag 'stat[]', 'runs', false %>R</span>&nbsp;
			<span title="Earned Runs"><%= check_box_tag 'stat[]', 'earned_runs', true %>ER</span>&nbsp;
			<br/>
			<span title="Home Runs"><%= check_box_tag 'stat[]', 'home_runs', false %>HR</span>&nbsp;
			<span title="Walks"><%= check_box_tag 'stat[]', 'walks', false %>BB</span>&nbsp;
			<span title="Strikeouts"><%= check_box_tag 'stat[]', 'strikeouts', true %>K</span>&nbsp;
			<span title="Intentional Walks"><%= check_box_tag 'stat[]', 'intentional_walks', false %>IBB</span>&nbsp;
			<span title="Wild Pitches"><%= check_box_tag 'stat[]', 'wild_pitches', false %>WP</span>&nbsp;
			<span title="Hit by Pitch"><%= check_box_tag 'stat[]', 'hit_by_pitch', false %>HBP</span>&nbsp;
			<span title="Balks"><%= check_box_tag 'stat[]', 'balks', false %>BK</span>&nbsp;
			<span title="Batters Faced"><%= check_box_tag 'stat[]', 'batters_faced', false %>BF</span>&nbsp;
			<span title="Games Finished"><%= check_box_tag 'stat[]', 'games_finished', false %>GF</span>&nbsp;
			<br/>
			<%= submit_tag 'Update' %>
		<% end %>
	</div>
	
	<br/>
	<br/>
	
	<div id = 'chart_select'>
		<span><p>Select a new statistic to change the charts</p></span>
		<%= form_tag change_career_chart_pitching_path(:players => @players), :remote => true, :id => "change_chart"  do %>
			<%= select_tag "chart_type", 
			raw("
			<option>Wins</option>
			<option>Losses</option>
			<option>Games</option>
			<option>Games Started</option>
			<option>Complete Games</option>
			<option>Shutouts</option>
			<option>Saves</option>
			<option>Hits</option>
			<option>Runs</option>
			<option>Earned Runs</option>
			<option>Home Runs</option>
			<option>Walks</option>
			<option>Strikeouts</option>
			<option>Intentional Walks</option>
			<option>Wild Pitches</option>
			<option>Hit by Pitch</option>
			<option>Balks</option>
			<option>Batters Faced</option>
			<option>Games Finished</option>
			") %>
			<%#= submit_tag 'Update' %>
		<% end %>
	</div>
	<br/>
	
	<div id = 'chart_place'>
		<%= render :partial => 'chart'  %> 
	</div>

        <script type="text/javascript">
          $('#chart_type').change(function(){
            $(this).parents('form:first').submit();
          });
        </script>

StatTracker/app/views/pitching_stats/index.html.erb
<% title "Pitching Stats" %>

<table>
  <tr>
    <th>Player</th>
    <th>Team</th>
    <th>Stint</th>
    <th>Wins</th>
    <th>Losses</th>
    <th>Games</th>
    <th>Games Started</th>
    <th>Complete Games</th>
    <th>Shutouts</th>
    <th>Saves</th>
    <th>Innings Pitched Outs</th>
    <th>Hits</th>
    <th>Earned Runs</th>
    <th>Home Runs</th>
    <th>Walks</th>
    <th>Strikeouts</th>
    <th>Intentional Walks</th>
    <th>Wild Pitches</th>
    <th>Hit By Pitch</th>
    <th>Balks</th>
    <th>Batters Faced</th>
    <th>Games Finished</th>
    <th>Runs</th>
    <th>Sacrifice Hits</th>
    <th>Sacrifice Flies</th>
    <th>Grounded Into Double Plays</th>
  </tr>
  <% for pitching_stat in @pitching_stats %>
    <tr>
      <td><%= pitching_stat.player_id %></td>
      <td><%= pitching_stat.team_id %></td>
      <td><%= pitching_stat.stint %></td>
      <td><%= pitching_stat.wins %></td>
      <td><%= pitching_stat.losses %></td>
      <td><%= pitching_stat.games %></td>
      <td><%= pitching_stat.games_started %></td>
      <td><%= pitching_stat.complete_games %></td>
      <td><%= pitching_stat.shutouts %></td>
      <td><%= pitching_stat.saves %></td>
      <td><%= pitching_stat.innings_pitched_outs %></td>
      <td><%= pitching_stat.hits %></td>
      <td><%= pitching_stat.earned_runs %></td>
      <td><%= pitching_stat.home_runs %></td>
      <td><%= pitching_stat.walks %></td>
      <td><%= pitching_stat.strikeouts %></td>
      <td><%= pitching_stat.intentional_walks %></td>
      <td><%= pitching_stat.wild_pitches %></td>
      <td><%= pitching_stat.hit_by_pitch %></td>
      <td><%= pitching_stat.balks %></td>
      <td><%= pitching_stat.batters_faced %></td>
      <td><%= pitching_stat.games_finished %></td>
      <td><%= pitching_stat.runs %></td>
      <td><%= pitching_stat.sacrifice_hits %></td>
      <td><%= pitching_stat.sacrifice_flies %></td>
      <td><%= pitching_stat.grounded_into_double_plays %></td>
      <td><%= link_to "Show", pitching_stat %></td>
      <td><%= link_to "Edit", edit_pitching_stat_path(pitching_stat) %></td>
      <td><%= link_to "Destroy", pitching_stat, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Pitching Stat", new_pitching_stat_path(pitching_stat) %></p>

StatTracker/app/views/pitching_stats/show.html.erb
<% title "Pitching Stat" %>

<p>
  <strong>Player:</strong>
  <%= @pitching_stat.player_id %>
</p>
<p>
  <strong>Team:</strong>
  <%= @pitching_stat.team_id %>
</p>
<p>
  <strong>Stint:</strong>
  <%= @pitching_stat.stint %>
</p>
<p>
  <strong>Wins:</strong>
  <%= @pitching_stat.wins %>
</p>
<p>
  <strong>Losses:</strong>
  <%= @pitching_stat.losses %>
</p>
<p>
  <strong>Games:</strong>
  <%= @pitching_stat.games %>
</p>
<p>
  <strong>Games Started:</strong>
  <%= @pitching_stat.games_started %>
</p>
<p>
  <strong>Complete Games:</strong>
  <%= @pitching_stat.complete_games %>
</p>
<p>
  <strong>Shutouts:</strong>
  <%= @pitching_stat.shutouts %>
</p>
<p>
  <strong>Saves:</strong>
  <%= @pitching_stat.saves %>
</p>
<p>
  <strong>Innings Pitched Outs:</strong>
  <%= @pitching_stat.innings_pitched_outs %>
</p>
<p>
  <strong>Hits:</strong>
  <%= @pitching_stat.hits %>
</p>
<p>
  <strong>Earned Runs:</strong>
  <%= @pitching_stat.earned_runs %>
</p>
<p>
  <strong>Home Runs:</strong>
  <%= @pitching_stat.home_runs %>
</p>
<p>
  <strong>Walks:</strong>
  <%= @pitching_stat.walks %>
</p>
<p>
  <strong>Strikeouts:</strong>
  <%= @pitching_stat.strikeouts %>
</p>
<p>
  <strong>Intentional Walks:</strong>
  <%= @pitching_stat.intentional_walks %>
</p>
<p>
  <strong>Wild Pitches:</strong>
  <%= @pitching_stat.wild_pitches %>
</p>
<p>
  <strong>Hit By Pitch:</strong>
  <%= @pitching_stat.hit_by_pitch %>
</p>
<p>
  <strong>Balks:</strong>
  <%= @pitching_stat.balks %>
</p>
<p>
  <strong>Batters Faced:</strong>
  <%= @pitching_stat.batters_faced %>
</p>
<p>
  <strong>Games Finished:</strong>
  <%= @pitching_stat.games_finished %>
</p>
<p>
  <strong>Runs:</strong>
  <%= @pitching_stat.runs %>
</p>
<p>
  <strong>Sacrifice Hits:</strong>
  <%= @pitching_stat.sacrifice_hits %>
</p>
<p>
  <strong>Sacrifice Flies:</strong>
  <%= @pitching_stat.sacrifice_flies %>
</p>
<p>
  <strong>Grounded Into Double Plays:</strong>
  <%= @pitching_stat.grounded_into_double_plays %>
</p>

<p>
  <%= link_to "Edit", edit_pitching_stat_path(@pitching_stat) %> |
  <%= link_to "Destroy", @pitching_stat, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", pitching_stats_path %>
</p>