StatTracker/config/routes.rb
StatTracker::Application.routes.draw do
  
  
  match 'index' => 'home#index', :as => 'home#index'
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  
  match 'compare' => 'home#compare', :as => 'home#compare'
  match 'franchise_compare' => 'home#franchise_compare'
  match 'home/google' => 'search#google_images', :as => 'home#google'
  match 'batting_leaderboards' => 'home#batting_leaderboard'
  match 'pitching_leaderboards' => 'home#pitching_leaderboard'
  match 'fielding_leaderboards' => 'home#fielding_leaderboard'
  match 'batting_leaders' => 'home#batting_leaders'
  match 'pitching_leaders' => 'home#pitching_leaders'
  match 'fielding_leaders' => 'home#fielding_leaders'
  match 'years_players' => 'home#years_players'
  match 'compare_players' => 'home#compare_players'
  
  match 'years_franchises' => 'home#years_franchises'
  match 'compare_franchises' => 'home#compare_franchises'

  match 'players/letter/' => 'players#by_letter', :as => :players_by_letter
  match 'players/letter/:letter' => 'players#letter', :as => :players_letter

  match 'players/position/' => 'players#by_position', :as => :players_by_position
  match 'players/position/:position' => 'players#position', :as => :players_position
  
  get 'home/autocomplete_player_name'
  get 'home/autocomplete_franchise_name'
  get 'players/autocomplete_player_name'
  get 'franchises/autocomplete_franchise_name'

  resources :teams

  resources :players

  resources :pitching_stats

  resources :pitching_post_stats

  resources :franchises

  resources :leagues

  resources :fielding_stats

  resources :fielding_post_stats

  resources :divisions

  resources :batting_stats

  resources :batting_post_stats
  
  match 'leaders/season/batting/:stat' => 'batting_stats#single_season'
  match 'leaders/season/batting_post/:stat' => 'batting_post_stats#single_season'
  match 'leaders/season/pitching/:stat' => 'pitching_stats#single_season'
  match 'leaders/season/pitching_post/:stat' => 'pitching_post_stats#single_season'
  match 'leaders/season/fielding/:stat' => 'fielding_stats#single_season'
  match 'leaders/season/fielding_post/:stat' => 'fielding_post_stats#single_season'
  
  match 'leaders/career/batting/:stat' => 'batting_stats#career'
  match 'leaders/career/batting_post/:stat' => 'batting_post_stats#career'
  match 'leaders/career/pitching/:stat' => 'pitching_stats#career'
  match 'leaders/career/pitching_post/:stat' => 'pitching_post_stats#career'
  match 'leaders/career/fielding/:stat' => 'fielding_stats#career'
  match 'leaders/career/fielding_post/:stat' => 'fielding_post_stats#career'

  match 'leaders/active/batting/:stat' => 'batting_stats#active'
  match 'leaders/active/batting_post/:stat' => 'batting_post_stats#active'
  match 'leaders/active/pitching/:stat' => 'pitching_stats#active'
  match 'leaders/active/pitching_post/:stat' => 'pitching_post_stats#active'
  match 'leaders/active/fielding/:stat' => 'fielding_stats#active'
  match 'leaders/active/fielding_post/:stat' => 'fielding_post_stats#active'
  
  match 'compare/season/batting/*comp' => 'batting_stats#season_compare'
  match 'compare/career/batting/*comp' => 'batting_stats#career_compare'
  match 'compare/multi/batting/*comp' => 'batting_stats#multi_compare'
  match 'compare/season/pitching/*comp' => 'pitching_stats#season_compare'
  match 'compare/career/pitching/*comp' => 'pitching_stats#career_compare'
  match 'compare/multi/pitching/*comp' => 'pitching_stats#multi_compare'

  match 'franchise_compare/season/*comp' => 'teams#season_compare'
  match 'franchise_compare/career/*comp' => 'teams#career_compare'
  match 'franchise_compare/multi/*comp' => 'teams#multi_compare'
  
  match 'seasonfinder/batting' => 'batting_stats#season_finder'
  match 'seasonfinder/batting/results' => 'batting_stats#find_seasons'
  match 'seasonfinder/pitching' => 'pitching_stats#season_finder'
  match 'seasonfinder/pitching/results' => 'pitching_stats#find_seasons'
  match 'seasonfinder/fielding' => 'fielding_stats#season_finder'
  match 'seasonfinder/fielding/results' => 'fielding_stats#find_seasons'
  
  match 'change_career_chart_batting' => 'batting_stats#change_career_chart'
  match 'change_career_table_batting' => 'batting_stats#change_career_table'
  match 'change_career_chart_pitching' => 'pitching_stats#change_career_chart'
  match 'change_career_table_pitching' => 'pitching_stats#change_career_table'
  match 'change_career_chart_team' => 'teams#change_career_chart'
  match 'change_career_table_team' => 'teams#change_career_table'
  
  match 'change_multi_chart_batting' => 'batting_stats#change_multi_chart'
  match 'change_multi_table_batting' => 'batting_stats#change_multi_table'
  match 'change_multi_chart_pitching' => 'pitching_stats#change_multi_chart'
  match 'change_multi_table_pitching' => 'pitching_stats#change_multi_table'
  match 'change_multi_chart_team' => 'teams#change_multi_chart'
  match 'change_multi_table_team' => 'teams#change_multi_table'
  
  match 'search' => 'home#search', :as => :search

  match 'team_search' => 'franchises#team_search', :as => :team_search
  match 'player_search' => 'players#player_search', :as => :player_search

   root :to => "home#index"

end

StatTracker/app/models/pitching_post_stat.rb
class PitchingPostStat < ActiveRecord::Base
    attr_accessible :player_id, :team_id, :round, :wins, :losses, :games, :games_started, :complete_games, :shutouts, :saves, :innings_pitched_outs, :hits, :earned_runs, :home_runs, :walks, :strikeouts, :intentional_walks, :wild_pitches, :hit_by_pitch, :balks, :batters_faced, :games_finished, :runs, :sacrifice_hits, :sacrifice_flies, :grounded_into_double_plays

	belongs_to :player
	belongs_to :team
	
	def self.get_stat_total(player, stat)
		stats = PitchingPostStat.find(:all, :select => [stat], :conditions => ['player_id = ?', player])
		count = 0
		stats.each { |s|
		count += s.send(stat)
		}
		count.to_s
	end

  def self.single_season_sort(stat)
		s = accessible_attributes.include?(stat)? stat.to_s + " DESC": send("str_" + stat)
		min_ip = accessible_attributes.include?(stat)? 0 : 45
		PitchingPostStat.find(:all, :conditions => ["innings_pitched_outs > ? AND batters_faced > ?", min_ip, 0], :order => s, :limit => 50)
	end

	def self.career_sort(stat)
		if accessible_attributes.include?(stat)
			stats = PitchingPostStat.find(:all, :select => [:player_id, stat.to_sym], :joins => [:player])
			comb = {}
			stats.each { |s|
				if comb.has_key?(s.player_id)
						comb[s.player_id] += s.send(stat).to_i
				else
					if (s.send(stat) == 0 || s.send(stat).nil?)
						comb.store(s.player_id, 0)
					else
						comb.store(s.player_id, s.send(stat))
					end
				end
			}
			sorted = comb.sort{|a,b| b[1] <=> a[1]}
			sorted.take(50).each { |a|
			a[0] = Player.find(a[0])
			}
			return sorted.take(50)
		else 
			s = "str_career_post_" + stat
			Player.find(:all, :conditions => ["career_innings_pitched_outs_post > ? AND career_batters_faced_post > ?", 45, 75], :order => Player.send(s), :limit => 50)
		end
	end

	def self.active_sort(stat)
		if accessible_attributes.include?(stat)
			stats = PitchingPostStat.find(:all, :select => [:player_id, stat.to_sym], :conditions => ["final_game is NULL"], :joins => [:player])
			puts stats
			comb = {}
			stats.each { |s|
				if comb.has_key?(s.player_id)
						comb[s.player_id] += s.send(stat).to_i
				else
					if (s.send(stat) == 0 || s.send(stat).nil?)
						comb.store(s.player_id, 0)
					else
						comb.store(s.player_id, s.send(stat))
					end
				end
			}
			sorted = comb.sort{|a,b| b[1] <=> a[1]}
			sorted.take(50).each { |a|
			a[0] = Player.find(a[0])
			}
			return sorted.take(50)
		else 
			s = "str_career_post_" + stat
			Player.find(:all, :conditions => ["career_innings_pitched_outs_post > ? AND career_batters_faced_post > ? AND final_game is NULL", 45, 75], :order => Player.send(s), :limit => 50)
		end
	end

	def year
		team.year
	end

	def win_loss_percentage()
		if (wins + losses) == 0
			sprintf("%.3f", 0)
		else sprintf("%.3f", (wins / (wins + losses).to_f))
		end
	end

	def innings_pitched_display
		ip = sprintf("%.1f", innings_pitched_outs / 3.to_f)
		if ip[ip.size-1] == '3'
			ip[ip.size-1] = '1'
		elsif ip[ip.size-1] == '7'
			ip[ip.size-1] = '2'
		else
		end
		ip
	end
	
	def innings_pitched
		innings_pitched_outs / 3.to_f
	end
	
	def era
		if innings_pitched == 0
			'INF'
		else sprintf("%.2f", (earned_runs * 9) / innings_pitched.to_f)
		end
	end

	def opponents_batting_average
		if (batters_faced - walks - hit_by_pitch - intentional_walks) == 0
			sprintf("%.2f", 0.to_f)
		else sprintf("%.3f", ((hits) / (batters_faced - walks - hit_by_pitch - intentional_walks).to_f))
		end
	end

	def walks_and_hits_innings_pitched
		if innings_pitched == 0
			'INF'
		else sprintf("%.2f", ((walks + hits) / innings_pitched.to_f))
		end
	end

	def hits_per_9_innings
		if innings_pitched == 0
			'INF'
		else sprintf("%.2f", ((hits * 9) / innings_pitched.to_f))
		end
	end

	def home_runs_per_9_innings
		if innings_pitched == 0
			'INF'
		else sprintf("%.2f", ((home_runs * 9) / innings_pitched.to_f))
		end
	end

	def walks_per_9_innings
		if innings_pitched == 0
			'INF'
		else sprintf("%.2f", ((walks * 9) / innings_pitched.to_f))
		end
	end

	def strikeouts_per_9_innings
		if innings_pitched == 0
			'INF'
		else sprintf("%.2f", ((strikeouts * 9) / innings_pitched.to_f))
		end
	end

	def strikeouts_per_walk
		if walks == 0
			'INF'
		else sprintf("%.2f", ((strikeouts / walks.to_f)))
		end
	end

	def adjusted_era
		league_era = PitchingStat.where(year => self.year).average(era)
		100 * (league_era / era)
	end

  private

  def self.multiplier
    10000
  end

  def self.str_win_loss_percentage()
		"((wins * #{multiplier}) / (wins + losses)) DESC"
	end

	def self.str_innings_pitched
		"innings_pitched_outs * #{multiplier} / 3 DESC"
	end

	def self.str_era
		"((earned_runs * 9) * #{multiplier}) / (innings_pitched_outs / 3) ASC"
	end

	def self.str_opponents_batting_average
		"(hits * #{multiplier}) / (batters_faced - walks - hit_by_pitch - intentional_walks) ASC"
	end

	def self.str_walks_and_hits_innings_pitched
		"(walks + hits) * #{multiplier} / (innings_pitched_outs / 3) ASC"
	end

	def self.str_hits_per_9_innings
		"(hits * 9) * #{multiplier} / (innings_pitched_outs / 3) ASC"
	end

	def self.str_home_runs_per_9_innings
		"(home_runs * 9) * #{multiplier} / (innings_pitched_outs / 3) ASC"
	end

	def self.str_walks_per_9_innings
		"(walks * 9) * #{multiplier} / (innings_pitched_outs / 3) ASC"
	end

	def self.str_strikeouts_per_9_innings
		"(strikeouts * 9) * #{multiplier} / (innings_pitched_outs / 3) DESC"
	end

	def self.str_strikeouts_per_walk
		"(strikeouts * #{multiplier} / walks) DESC"
	end

	def self.str_adjusted_era
		league_era = PitchingStat.where(year => self.year).average(era)
		"100 * #{multiplier} * (#{league_era} / era) DESC"
	end
end

StatTracker/app/controllers/pitching_post_stats_controller.rb
class PitchingPostStatsController < ApplicationController
  def index
    @pitching_post_stats = PitchingPostStat.all
  end

  def show
    @pitching_post_stat = PitchingPostStat.find(params[:id])
  end
  
    def single_season
		@pitching_post_stats = PitchingPostStat.single_season_sort(params[:stat])
		@table = GoogleVisualr::Table.new
		@table.add_column('string' , 'Name')
		@table.add_column('string' , 'Throws')
		@table.add_column('string' , 'Team')
		@table.add_column('string' , 'Year')
		if params[:stat] == 'era'
			@table.add_column('string' , params[:stat].upcase)
		else @table.add_column('string' , params[:stat].titleize)
		end
		@table.add_rows(50)
		@pitching_post_stats.each { |b|
			
			i = @pitching_post_stats.index(b)
			@table.set_cell(i, 0, "<a href='/players/#{b.player.id}'>#{b.player.name}</a>")
			if !b.player.throws.nil?
				@table.set_cell(i, 1, b.player.throws)
			else @table.set_cell(i, 1, 'N/A')
			end
			@table.set_cell(i, 2, "<a href='/teams/#{b.team.id}'>#{b.team.name}</a>")
			@table.set_cell(i, 3, "#{b.year}")
			@table.set_cell(i, 4, "#{b.send(params[:stat])}")
		}
		
		options = { :width => 600, :showRowNumber => true, :allowHtml=>true }
		options.each_pair do | key, value |
			@table.send "#{key}=", value
		end	
	end
  
    def career
		@pitching_post_stats = PitchingPostStat.career_sort(params[:stat])
		@table = GoogleVisualr::Table.new
		@table.add_column('string' , 'Name')
		@table.add_column('string' , 'Throws')
		if params[:stat] == 'era'
			@table.add_column('string' , params[:stat].upcase)
		else @table.add_column('string' , params[:stat].titleize)
		end
		@table.add_rows(50)
		i = 0
			if PitchingPostStat.accessible_attributes.include?(params[:stat])
				@pitching_post_stats.each { |k, v|
					@table.set_cell(i, 0, "<a href='/players/#{k.id}'>#{k.name}</a>")
					if !k.throws.nil?
						@table.set_cell(i, 1, k.throws)
					else @table.set_cell(i, 1, 'N/A')
					end
					@table.set_cell(i, 2, "#{v}")
					i += 1
				}
			else 
				@pitching_post_stats.each { |b|
					@table.set_cell(i, 0, "<a href='/players/#{b.id}'>#{b.name}</a>")
					if !b.bats.nil?
						@table.set_cell(i, 1, b.bats)
					else @table.set_cell(i, 1, 'N/A')
					end
					@table.set_cell(i, 2, "#{b.send("career_post_" + params[:stat])}")
					i += 1
				}
			end
			
		options = { :width => 600, :showRowNumber => true, :allowHtml=>true }
		options.each_pair do | key, value |
			@table.send "#{key}=", value
		end
	end
	
	def active
		@pitching_post_stats = PitchingPostStat.active_sort(params[:stat])
		@table = GoogleVisualr::Table.new
		@table.add_column('string' , 'Name')
		@table.add_column('string' , 'Throws')
		if params[:stat] == 'era'
			@table.add_column('string' , params[:stat].upcase)
		else @table.add_column('string' , params[:stat].titleize)
		end
		@table.add_rows(50)
		i = 0
			if PitchingPostStat.accessible_attributes.include?(params[:stat])
				@pitching_post_stats.each { |k, v|
					@table.set_cell(i, 0, "<a href='/players/#{k.id}'>#{k.name}</a>")
					if !k.throws.nil?
						@table.set_cell(i, 1, k.throws)
					else @table.set_cell(i, 1, 'N/A')
					end
					@table.set_cell(i, 2, "#{v}")
					i += 1
				}
			else 
				@pitching_post_stats.each { |b|
					@table.set_cell(i, 0, "<a href='/players/#{b.id}'>#{b.name}</a>")
					if !b.bats.nil?
						@table.set_cell(i, 1, b.bats)
					else @table.set_cell(i, 1, 'N/A')
					end
					@table.set_cell(i, 2, "#{b.send("career_post_" + params[:stat])}")
					i += 1
				}
			end	
		options = { :width => 600, :showRowNumber => true, :allowHtml=>true }
		options.each_pair do | key, value |
			@table.send "#{key}=", value
		end
	end

  def season_finder

  end

  def find_seasons
    number = params[:fields][:count].to_i
    @stats = []
    operations = []
    (1..number).each do |i|
      stat = params["#{i}"][:stat]
      next if stat.blank?
      operator = params["#{i}"][:operator]
      number = params["#{i}"][:number]
      string = stat + " " + operator + " " + number
      @stats.push(stat)
      operations.push(string)
    end
    @batting_stats = PitchingPostStat.where(operations.join(" AND "))

  end
	
end

StatTracker/app/helpers/pitching_post_stats_helper.rb
module PitchingPostStatsHelper
end

StatTracker/app/views/pitching_post_stats/_form.html.erb
<%= form_for @pitching_post_stat do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :player_id %><br />
    <%= f.text_field :player_id %>
  </p>
  <p>
    <%= f.label :team_id %><br />
    <%= f.text_field :team_id %>
  </p>
  <p>
    <%= f.label :round %><br />
    <%= f.text_field :round %>
  </p>
  <p>
    <%= f.label :wins %><br />
    <%= f.text_field :wins %>
  </p>
  <p>
    <%= f.label :losses %><br />
    <%= f.text_field :losses %>
  </p>
  <p>
    <%= f.label :games %><br />
    <%= f.text_field :games %>
  </p>
  <p>
    <%= f.label :games_started %><br />
    <%= f.text_field :games_started %>
  </p>
  <p>
    <%= f.label :complete_games %><br />
    <%= f.text_field :complete_games %>
  </p>
  <p>
    <%= f.label :shutouts %><br />
    <%= f.text_field :shutouts %>
  </p>
  <p>
    <%= f.label :saves %><br />
    <%= f.text_field :saves %>
  </p>
  <p>
    <%= f.label :innings_pitched_outs %><br />
    <%= f.text_field :innings_pitched_outs %>
  </p>
  <p>
    <%= f.label :hits %><br />
    <%= f.text_field :hits %>
  </p>
  <p>
    <%= f.label :earned_runs %><br />
    <%= f.text_field :earned_runs %>
  </p>
  <p>
    <%= f.label :home_runs %><br />
    <%= f.text_field :home_runs %>
  </p>
  <p>
    <%= f.label :walks %><br />
    <%= f.text_field :walks %>
  </p>
  <p>
    <%= f.label :strikeouts %><br />
    <%= f.text_field :strikeouts %>
  </p>
  <p>
    <%= f.label :intentional_walks %><br />
    <%= f.text_field :intentional_walks %>
  </p>
  <p>
    <%= f.label :wild_pitches %><br />
    <%= f.text_field :wild_pitches %>
  </p>
  <p>
    <%= f.label :hit_by_pitch %><br />
    <%= f.text_field :hit_by_pitch %>
  </p>
  <p>
    <%= f.label :balks %><br />
    <%= f.text_field :balks %>
  </p>
  <p>
    <%= f.label :batters_faced %><br />
    <%= f.text_field :batters_faced %>
  </p>
  <p>
    <%= f.label :games_finished %><br />
    <%= f.text_field :games_finished %>
  </p>
  <p>
    <%= f.label :runs %><br />
    <%= f.text_field :runs %>
  </p>
  <p>
    <%= f.label :sacrifice_hits %><br />
    <%= f.text_field :sacrifice_hits %>
  </p>
  <p>
    <%= f.label :sacrifice_flies %><br />
    <%= f.text_field :sacrifice_flies %>
  </p>
  <p>
    <%= f.label :grounded_into_double_plays %><br />
    <%= f.text_field :grounded_into_double_plays %>
  </p>
  <p><%= f.submit %></p>
<% end %>

StatTracker/app/views/pitching_post_stats/active.html.erb
<% if params[:stat] == 'era' %>
	<h1><% title params[:stat].upcase + " Active Post Season Leaders" %></h1>
<% else %>
	<h1><% title params[:stat].titleize + " Active Post Season Leaders" %></h1>
<% end %>

	<div id = 'chart'></div>
	<%= raw @table.render('chart') %>

StatTracker/app/views/pitching_post_stats/career.html.erb
<% if params[:stat] == 'era' %>
	<h1><% title params[:stat].upcase + " Career Post Season Leaders" %></h1>
<% else %>
	<h1><% title params[:stat].titleize + " Career Post Season Leaders" %></h1>
<% end %>

	<div id = 'chart'></div>
	<%= raw @table.render('chart') %>

StatTracker/app/views/pitching_post_stats/find_seasons.html.erb
<% title "Batting Season Finder" %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Team</th>
      <th>Year</th>
      <% @stats.each do |i| %>
      <th><%= i.titleize %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @batting_stats.each do |stat| %>
    <tr>
      <td><%= stat.player.name %></td>
      <td><%= stat.team.name %></td>
      <td><%= stat.year %></td>
      <% @stats.each do |i| %>
      <td><%= stat.send(i) %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

StatTracker/app/views/pitching_post_stats/index.html.erb
<% title "Pitching Post Stats" %>

<table>
  <tr>
    <th>Player</th>
    <th>Team</th>
    <th>Round</th>
    <th>Wins</th>
    <th>Losses</th>
    <th>Games</th>
    <th>Games Started</th>
    <th>Complete Games</th>
    <th>Shutouts</th>
    <th>Saves</th>
    <th>Innings Pitched Outs</th>
    <th>Hits</th>
    <th>Earned Runs</th>
    <th>Home Runs</th>
    <th>Walks</th>
    <th>Strikeouts</th>
    <th>Intentional Walks</th>
    <th>Wild Pitches</th>
    <th>Hit By Pitch</th>
    <th>Balks</th>
    <th>Batters Faced</th>
    <th>Games Finished</th>
    <th>Runs</th>
    <th>Sacrifice Hits</th>
    <th>Sacrifice Flies</th>
    <th>Grounded Into Double Plays</th>
  </tr>
  <% for pitching_post_stat in @pitching_post_stats %>
    <tr>
      <td><%= pitching_post_stat.player_id %></td>
      <td><%= pitching_post_stat.team_id %></td>
      <td><%= pitching_post_stat.round %></td>
      <td><%= pitching_post_stat.wins %></td>
      <td><%= pitching_post_stat.losses %></td>
      <td><%= pitching_post_stat.games %></td>
      <td><%= pitching_post_stat.games_started %></td>
      <td><%= pitching_post_stat.complete_games %></td>
      <td><%= pitching_post_stat.shutouts %></td>
      <td><%= pitching_post_stat.saves %></td>
      <td><%= pitching_post_stat.innings_pitched_outs %></td>
      <td><%= pitching_post_stat.hits %></td>
      <td><%= pitching_post_stat.earned_runs %></td>
      <td><%= pitching_post_stat.home_runs %></td>
      <td><%= pitching_post_stat.walks %></td>
      <td><%= pitching_post_stat.strikeouts %></td>
      <td><%= pitching_post_stat.intentional_walks %></td>
      <td><%= pitching_post_stat.wild_pitches %></td>
      <td><%= pitching_post_stat.hit_by_pitch %></td>
      <td><%= pitching_post_stat.balks %></td>
      <td><%= pitching_post_stat.batters_faced %></td>
      <td><%= pitching_post_stat.games_finished %></td>
      <td><%= pitching_post_stat.runs %></td>
      <td><%= pitching_post_stat.sacrifice_hits %></td>
      <td><%= pitching_post_stat.sacrifice_flies %></td>
      <td><%= pitching_post_stat.grounded_into_double_plays %></td>
      <td><%= link_to "Show", pitching_post_stat %></td>
      <td><%= link_to "Edit", edit_pitching_post_stat_path(pitching_post_stat) %></td>
      <td><%= link_to "Destroy", pitching_post_stat, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Pitching Post Stat", new_pitching_post_stat_path(pitching_post_stat) %></p>

StatTracker/app/views/pitching_post_stats/season_finder.html.erb
<% title "Postseason Pitching Season Finder" %>
<%= form_tag :controller => :batting_stats, :action => :find_seasons do |f| %>
  <% number = 5 %>
  <%= hidden_field "fields", "count", {:value => number, :id => "count"} %>
  <% (1..number).each do |i| %>
      <%= select_tag "#{i}[stat]", options_for_select(PitchingPostStat.accessible_attributes), :include_blank => true %>
      <%= select_tag "#{i}[operator]", options_for_select(%w(= < <= > >=)) %>
      <%= text_field "#{i}", "number", :size => 5 %><br />
  <% end %>
  <%= submit_tag "Find Seasons" %>
<% end %>

StatTracker/app/views/pitching_post_stats/show.html.erb
<% title "Pitching Post Stat" %>

<p>
  <strong>Player:</strong>
  <%= @pitching_post_stat.player_id %>
</p>
<p>
  <strong>Team:</strong>
  <%= @pitching_post_stat.team_id %>
</p>
<p>
  <strong>Round:</strong>
  <%= @pitching_post_stat.round %>
</p>
<p>
  <strong>Wins:</strong>
  <%= @pitching_post_stat.wins %>
</p>
<p>
  <strong>Losses:</strong>
  <%= @pitching_post_stat.losses %>
</p>
<p>
  <strong>Games:</strong>
  <%= @pitching_post_stat.games %>
</p>
<p>
  <strong>Games Started:</strong>
  <%= @pitching_post_stat.games_started %>
</p>
<p>
  <strong>Complete Games:</strong>
  <%= @pitching_post_stat.complete_games %>
</p>
<p>
  <strong>Shutouts:</strong>
  <%= @pitching_post_stat.shutouts %>
</p>
<p>
  <strong>Saves:</strong>
  <%= @pitching_post_stat.saves %>
</p>
<p>
  <strong>Innings Pitched Outs:</strong>
  <%= @pitching_post_stat.innings_pitched_outs %>
</p>
<p>
  <strong>Hits:</strong>
  <%= @pitching_post_stat.hits %>
</p>
<p>
  <strong>Earned Runs:</strong>
  <%= @pitching_post_stat.earned_runs %>
</p>
<p>
  <strong>Home Runs:</strong>
  <%= @pitching_post_stat.home_runs %>
</p>
<p>
  <strong>Walks:</strong>
  <%= @pitching_post_stat.walks %>
</p>
<p>
  <strong>Strikeouts:</strong>
  <%= @pitching_post_stat.strikeouts %>
</p>
<p>
  <strong>Intentional Walks:</strong>
  <%= @pitching_post_stat.intentional_walks %>
</p>
<p>
  <strong>Wild Pitches:</strong>
  <%= @pitching_post_stat.wild_pitches %>
</p>
<p>
  <strong>Hit By Pitch:</strong>
  <%= @pitching_post_stat.hit_by_pitch %>
</p>
<p>
  <strong>Balks:</strong>
  <%= @pitching_post_stat.balks %>
</p>
<p>
  <strong>Batters Faced:</strong>
  <%= @pitching_post_stat.batters_faced %>
</p>
<p>
  <strong>Games Finished:</strong>
  <%= @pitching_post_stat.games_finished %>
</p>
<p>
  <strong>Runs:</strong>
  <%= @pitching_post_stat.runs %>
</p>
<p>
  <strong>Sacrifice Hits:</strong>
  <%= @pitching_post_stat.sacrifice_hits %>
</p>
<p>
  <strong>Sacrifice Flies:</strong>
  <%= @pitching_post_stat.sacrifice_flies %>
</p>
<p>
  <strong>Grounded Into Double Plays:</strong>
  <%= @pitching_post_stat.grounded_into_double_plays %>
</p>

<p>
  <%= link_to "Edit", edit_pitching_post_stat_path(@pitching_post_stat) %> |
  <%= link_to "Destroy", @pitching_post_stat, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", pitching_post_stats_path %>
</p>

StatTracker/app/views/pitching_post_stats/single_season.html.erb
<% if params[:stat] == 'era' %>
	<h1><% title params[:stat].upcase + " Single Post Season Leaders" %></h1>
<% else %>
	<h1><% title params[:stat].titleize + " Single Post Season Leaders" %></h1>
<% end %>

	<div id = 'chart'></div>
	<%= raw @table.render('chart') %>