StatTracker/config/routes.rb
StatTracker::Application.routes.draw do
  
  
  match 'index' => 'home#index', :as => 'home#index'
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  
  match 'compare' => 'home#compare', :as => 'home#compare'
  match 'franchise_compare' => 'home#franchise_compare'
  match 'home/google' => 'search#google_images', :as => 'home#google'
  match 'batting_leaderboards' => 'home#batting_leaderboard'
  match 'pitching_leaderboards' => 'home#pitching_leaderboard'
  match 'fielding_leaderboards' => 'home#fielding_leaderboard'
  match 'batting_leaders' => 'home#batting_leaders'
  match 'pitching_leaders' => 'home#pitching_leaders'
  match 'fielding_leaders' => 'home#fielding_leaders'
  match 'years_players' => 'home#years_players'
  match 'compare_players' => 'home#compare_players'
  
  match 'years_franchises' => 'home#years_franchises'
  match 'compare_franchises' => 'home#compare_franchises'

  match 'players/letter/' => 'players#by_letter', :as => :players_by_letter
  match 'players/letter/:letter' => 'players#letter', :as => :players_letter

  match 'players/position/' => 'players#by_position', :as => :players_by_position
  match 'players/position/:position' => 'players#position', :as => :players_position
  
  get 'home/autocomplete_player_name'
  get 'home/autocomplete_franchise_name'
  get 'players/autocomplete_player_name'
  get 'franchises/autocomplete_franchise_name'

  resources :teams

  resources :players

  resources :pitching_stats

  resources :pitching_post_stats

  resources :franchises

  resources :leagues

  resources :fielding_stats

  resources :fielding_post_stats

  resources :divisions

  resources :batting_stats

  resources :batting_post_stats
  
  match 'leaders/season/batting/:stat' => 'batting_stats#single_season'
  match 'leaders/season/batting_post/:stat' => 'batting_post_stats#single_season'
  match 'leaders/season/pitching/:stat' => 'pitching_stats#single_season'
  match 'leaders/season/pitching_post/:stat' => 'pitching_post_stats#single_season'
  match 'leaders/season/fielding/:stat' => 'fielding_stats#single_season'
  match 'leaders/season/fielding_post/:stat' => 'fielding_post_stats#single_season'
  
  match 'leaders/career/batting/:stat' => 'batting_stats#career'
  match 'leaders/career/batting_post/:stat' => 'batting_post_stats#career'
  match 'leaders/career/pitching/:stat' => 'pitching_stats#career'
  match 'leaders/career/pitching_post/:stat' => 'pitching_post_stats#career'
  match 'leaders/career/fielding/:stat' => 'fielding_stats#career'
  match 'leaders/career/fielding_post/:stat' => 'fielding_post_stats#career'

  match 'leaders/active/batting/:stat' => 'batting_stats#active'
  match 'leaders/active/batting_post/:stat' => 'batting_post_stats#active'
  match 'leaders/active/pitching/:stat' => 'pitching_stats#active'
  match 'leaders/active/pitching_post/:stat' => 'pitching_post_stats#active'
  match 'leaders/active/fielding/:stat' => 'fielding_stats#active'
  match 'leaders/active/fielding_post/:stat' => 'fielding_post_stats#active'
  
  match 'compare/season/batting/*comp' => 'batting_stats#season_compare'
  match 'compare/career/batting/*comp' => 'batting_stats#career_compare'
  match 'compare/multi/batting/*comp' => 'batting_stats#multi_compare'
  match 'compare/season/pitching/*comp' => 'pitching_stats#season_compare'
  match 'compare/career/pitching/*comp' => 'pitching_stats#career_compare'
  match 'compare/multi/pitching/*comp' => 'pitching_stats#multi_compare'

  match 'franchise_compare/season/*comp' => 'teams#season_compare'
  match 'franchise_compare/career/*comp' => 'teams#career_compare'
  match 'franchise_compare/multi/*comp' => 'teams#multi_compare'
  
  match 'seasonfinder/batting' => 'batting_stats#season_finder'
  match 'seasonfinder/batting/results' => 'batting_stats#find_seasons'
  match 'seasonfinder/pitching' => 'pitching_stats#season_finder'
  match 'seasonfinder/pitching/results' => 'pitching_stats#find_seasons'
  match 'seasonfinder/fielding' => 'fielding_stats#season_finder'
  match 'seasonfinder/fielding/results' => 'fielding_stats#find_seasons'
  
  match 'change_career_chart_batting' => 'batting_stats#change_career_chart'
  match 'change_career_table_batting' => 'batting_stats#change_career_table'
  match 'change_career_chart_pitching' => 'pitching_stats#change_career_chart'
  match 'change_career_table_pitching' => 'pitching_stats#change_career_table'
  match 'change_career_chart_team' => 'teams#change_career_chart'
  match 'change_career_table_team' => 'teams#change_career_table'
  
  match 'change_multi_chart_batting' => 'batting_stats#change_multi_chart'
  match 'change_multi_table_batting' => 'batting_stats#change_multi_table'
  match 'change_multi_chart_pitching' => 'pitching_stats#change_multi_chart'
  match 'change_multi_table_pitching' => 'pitching_stats#change_multi_table'
  match 'change_multi_chart_team' => 'teams#change_multi_chart'
  match 'change_multi_table_team' => 'teams#change_multi_table'
  
  match 'search' => 'home#search', :as => :search

  match 'team_search' => 'franchises#team_search', :as => :team_search
  match 'player_search' => 'players#player_search', :as => :player_search

   root :to => "home#index"

end

StatTracker/app/controllers/franchises_controller.rb
class FranchisesController < ApplicationController
autocomplete :franchise, :name, :full => true

  def index
    @franchises = Franchise.all
  end

  def show
    @franchise = Franchise.find(params[:id])
    @google_image = GoogleImage.all(@franchise.name+" current logo", 0).first
    @teams= Team.find(:all, :conditions => ['franchise_id = ?', params[:id]])
    @first_team=@teams.first
    if !@franchise.active
    @last_team=@teams.last
    end
    @teams.reverse!
    @chart = GoogleVisualr::Table.new
		@chart.add_column('string' , 'Team')
    @chart.add_column('number' , 'Year')
		@chart.add_column('string' , 'League')
		@chart.add_column('number' , 'Wins')
		@chart.add_column('number' , 'Losses')
    @chart.add_column('string' , 'W-L%')
    @chart.add_column('string' , 'Rank')
    @chart.add_rows(@teams.size)
    @teams.each { |b|
			i = @teams.index(b)
			@chart.set_cell(i, 0, "<a href='/teams/#{b.id}'>#{b.name}</a>")
			@chart.set_cell(i, 1, b.year)
      @chart.set_cell(i, 2, b.division.league.name)
      @chart.set_cell(i, 3, b.wins)
      @chart.set_cell(i, 4, b.losses)
      @chart.set_cell(i, 5, b.pct.to_s)
      @chart.set_cell(i, 6, b.rank.to_s)
    }
    options = { :width => 600, :allowHtml => true}
    options.each_pair do | key, value |
    @chart.send "#{key}=", value
  end
  end

    def team_search
    @query = params[:query]
    @franchises = Franchise.search(@query)
    @total_hits = @franchises.size
    if @total_hits == 1
      if @franchises.first != nil
        redirect_to @franchises.first
      end
    end
  end


end

StatTracker/app/helpers/franchises_helper.rb
module FranchisesHelper
end

StatTracker/app/views/franchises/_form.html.erb
<%= form_for @franchise do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </p>
  <p><%= f.submit %></p>
<% end %>

StatTracker/app/views/franchises/index.html.erb
<% title "Teams" %>
    <tr>
      <th><b> Search by Team Name </b></th>
            <%= form_tag(team_search_path) do %>
                    <%= text_field_tag('query','',:size => 15,:placeholder => 'Enter a team..', :class => 'field_style', :autocomplete => franchises_autocomplete_franchise_name_path) %>
                    <%= submit_tag('Search') %>
            <% end %>
    </tr>
    <br />
    <br />

      <table>
        <th><b> Active Teams </b></th>
           <% for franchise in @franchises %>
            <% if franchise.active %>
                  <tr>
                    <td align="center"><%= link_to franchise.name, franchise_path(franchise) %></td>
                    <!-- <td><%= link_to "Show", franchise %></td> -->
                    <!-- <td><%= link_to "Edit", edit_franchise_path(franchise) %></td> -->
                    <!-- <td><%= link_to "Destroy", franchise, :confirm => 'Are you sure?', :method => :delete %></td> -->
                  </tr>
          <% end %>
          <% end %>

      </table>

StatTracker/app/views/franchises/show.html.erb
<% title @franchise.name %>
<% if @franchise.active%>
<%= image_tag(@google_image.original,:style => 'padding:3px; border:solid 1px #EEE; margin:2px; width:200px; height:auto; position:absolute; right:120px;') %>
<% end %>
<% if !@franchise.active %>
<p>
<strong>Active: &#10008 </strong>
</p>
<p>
  <strong>Years:</strong>
  <%= @first_team.year%>-<%= @last_team.year%>
</p>
<%  else %>
<p>
  <strong>Active: &#10004</strong>
</p>
<p>
  <strong>Years:</strong>
  <%= @first_team.year%>-
</p>
<% end %>
<div id='chart'></div>
<%= raw @chart.render('chart') %>

StatTracker/app/views/franchises/team_search.html.erb
<h1> Search Result </h1>
<% if @franchises.empty? %>
<br />
<h2>No teams found</h2>
<% end %>
<p class="supertiny">&nbsp;</p>

<% unless @franchises.empty? %>
	<p><em><strong>Teams matching term '<%= @query %>'</strong></em></p>
	<ul>
            <table class="datagrid">
              <thead class="datagrid">
                  <th width="250">Name</th>
                  <th width="250">Active</th>
                  <th>Year</th>
              </thead>
              <% for franchise in @franchises do %>
              <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
                  <td align ="center"><%= link_to franchise.name, franchise_path(franchise) %></td>
                  <td align ="center">
                      <% if franchise.active %>
                          <strong></strong>&#10004
                      <% end %>
                      <% if !franchise.active %>
                          <strong></strong>&#10008
                      <% end %>
                  </td>
                  <td align ="center">
                      <%=  "#{franchise.teams.first.year}" %>-<%=  "#{franchise.teams.last.year}" if !franchise.active? %>
                  </td>
              </tr>
            <% end %>
            </table>
	</ul>
	<p class="smtext">&nbsp;</p>
<% end %>