StatTracker/config/routes.rb
StatTracker::Application.routes.draw do
  
  
  match 'index' => 'home#index', :as => 'home#index'
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  
  match 'compare' => 'home#compare', :as => 'home#compare'
  match 'franchise_compare' => 'home#franchise_compare'
  match 'home/google' => 'search#google_images', :as => 'home#google'
  match 'batting_leaderboards' => 'home#batting_leaderboard'
  match 'pitching_leaderboards' => 'home#pitching_leaderboard'
  match 'fielding_leaderboards' => 'home#fielding_leaderboard'
  match 'batting_leaders' => 'home#batting_leaders'
  match 'pitching_leaders' => 'home#pitching_leaders'
  match 'fielding_leaders' => 'home#fielding_leaders'
  match 'years_players' => 'home#years_players'
  match 'compare_players' => 'home#compare_players'
  
  match 'years_franchises' => 'home#years_franchises'
  match 'compare_franchises' => 'home#compare_franchises'

  match 'players/letter/' => 'players#by_letter', :as => :players_by_letter
  match 'players/letter/:letter' => 'players#letter', :as => :players_letter

  match 'players/position/' => 'players#by_position', :as => :players_by_position
  match 'players/position/:position' => 'players#position', :as => :players_position
  
  get 'home/autocomplete_player_name'
  get 'home/autocomplete_franchise_name'
  get 'players/autocomplete_player_name'
  get 'franchises/autocomplete_franchise_name'

  resources :teams

  resources :players

  resources :pitching_stats

  resources :pitching_post_stats

  resources :franchises

  resources :leagues

  resources :fielding_stats

  resources :fielding_post_stats

  resources :divisions

  resources :batting_stats

  resources :batting_post_stats
  
  match 'leaders/season/batting/:stat' => 'batting_stats#single_season'
  match 'leaders/season/batting_post/:stat' => 'batting_post_stats#single_season'
  match 'leaders/season/pitching/:stat' => 'pitching_stats#single_season'
  match 'leaders/season/pitching_post/:stat' => 'pitching_post_stats#single_season'
  match 'leaders/season/fielding/:stat' => 'fielding_stats#single_season'
  match 'leaders/season/fielding_post/:stat' => 'fielding_post_stats#single_season'
  
  match 'leaders/career/batting/:stat' => 'batting_stats#career'
  match 'leaders/career/batting_post/:stat' => 'batting_post_stats#career'
  match 'leaders/career/pitching/:stat' => 'pitching_stats#career'
  match 'leaders/career/pitching_post/:stat' => 'pitching_post_stats#career'
  match 'leaders/career/fielding/:stat' => 'fielding_stats#career'
  match 'leaders/career/fielding_post/:stat' => 'fielding_post_stats#career'

  match 'leaders/active/batting/:stat' => 'batting_stats#active'
  match 'leaders/active/batting_post/:stat' => 'batting_post_stats#active'
  match 'leaders/active/pitching/:stat' => 'pitching_stats#active'
  match 'leaders/active/pitching_post/:stat' => 'pitching_post_stats#active'
  match 'leaders/active/fielding/:stat' => 'fielding_stats#active'
  match 'leaders/active/fielding_post/:stat' => 'fielding_post_stats#active'
  
  match 'compare/season/batting/*comp' => 'batting_stats#season_compare'
  match 'compare/career/batting/*comp' => 'batting_stats#career_compare'
  match 'compare/multi/batting/*comp' => 'batting_stats#multi_compare'
  match 'compare/season/pitching/*comp' => 'pitching_stats#season_compare'
  match 'compare/career/pitching/*comp' => 'pitching_stats#career_compare'
  match 'compare/multi/pitching/*comp' => 'pitching_stats#multi_compare'

  match 'franchise_compare/season/*comp' => 'teams#season_compare'
  match 'franchise_compare/career/*comp' => 'teams#career_compare'
  match 'franchise_compare/multi/*comp' => 'teams#multi_compare'
  
  match 'seasonfinder/batting' => 'batting_stats#season_finder'
  match 'seasonfinder/batting/results' => 'batting_stats#find_seasons'
  match 'seasonfinder/pitching' => 'pitching_stats#season_finder'
  match 'seasonfinder/pitching/results' => 'pitching_stats#find_seasons'
  match 'seasonfinder/fielding' => 'fielding_stats#season_finder'
  match 'seasonfinder/fielding/results' => 'fielding_stats#find_seasons'
  
  match 'change_career_chart_batting' => 'batting_stats#change_career_chart'
  match 'change_career_table_batting' => 'batting_stats#change_career_table'
  match 'change_career_chart_pitching' => 'pitching_stats#change_career_chart'
  match 'change_career_table_pitching' => 'pitching_stats#change_career_table'
  match 'change_career_chart_team' => 'teams#change_career_chart'
  match 'change_career_table_team' => 'teams#change_career_table'
  
  match 'change_multi_chart_batting' => 'batting_stats#change_multi_chart'
  match 'change_multi_table_batting' => 'batting_stats#change_multi_table'
  match 'change_multi_chart_pitching' => 'pitching_stats#change_multi_chart'
  match 'change_multi_table_pitching' => 'pitching_stats#change_multi_table'
  match 'change_multi_chart_team' => 'teams#change_multi_chart'
  match 'change_multi_table_team' => 'teams#change_multi_table'
  
  match 'search' => 'home#search', :as => :search

  match 'team_search' => 'franchises#team_search', :as => :team_search
  match 'player_search' => 'players#player_search', :as => :player_search

   root :to => "home#index"

end

StatTracker/app/controllers/batting_stats_controller.rb
class BattingStatsController < ApplicationController
include ApplicationHelper

  def index
    @batting_stats = BattingStat.all
  end

  def show
    @batting_stat = BattingStat.find(params[:id])
  end

	def single_season
		@batting_stats = BattingStat.single_season_sort(params[:stat])
		@table = GoogleVisualr::Table.new
		@table.add_column('string' , 'Name')
		@table.add_column('string' , 'Bats')
		@table.add_column('string' , 'Team')
		@table.add_column('string' , 'Year')
		if params[:stat] == 'rbi'
			@table.add_column('string' , params[:stat].upcase)
		else @table.add_column('string' , params[:stat].titleize)
		end
		@table.add_rows(50)
		@batting_stats.each { |b|
			i = @batting_stats.index(b)
			@table.set_cell(i, 0, "<a href='/players/#{b.player.id}'>#{b.player.name}</a>")
			if !b.player.bats.nil?
				@table.set_cell(i, 1, b.player.bats)
			else @table.set_cell(i, 1, 'N/A')
			end
			@table.set_cell(i, 2, "<a href='/teams/#{b.team.id}'>#{b.team.name}</a>")
			@table.set_cell(i, 3, "#{b.year}")
			@table.set_cell(i, 4, "#{b.send(params[:stat])}")
		}
		
		options = { :width => 600, :showRowNumber => true, :allowHtml => true}
		options.each_pair do | key, value |
			@table.send "#{key}=", value
		end	
	end
  
	def career
		@batting_stats = BattingStat.career_sort(params[:stat])
		@table = GoogleVisualr::Table.new
		@table.add_column('string' , 'Name')
		@table.add_column('string' , 'Bats')
		if params[:stat] == 'rbi'
			@table.add_column('string' , params[:stat].upcase)
		else @table.add_column('string' , params[:stat].titleize)
		end
		@table.add_rows(50)
		i = 0
			if BattingStat.accessible_attributes.include?(params[:stat])
				@batting_stats.each { |k, v|
					@table.set_cell(i, 0, "<a href='/players/#{k.id}'>#{k.name}</a>")
					if !k.bats.nil?
						@table.set_cell(i, 1, k.bats)
					else @table.set_cell(i, 1, 'N/A')
					end
					@table.set_cell(i, 2, "#{v}")
					i += 1
				}
			else 
				@batting_stats.each { |b|
					@table.set_cell(i, 0, "<a href='/players/#{b.id}'>#{b.name}</a>")
					if !b.bats.nil?
						@table.set_cell(i, 1, b.bats)
					else @table.set_cell(i, 1, 'N/A')
					end
					@table.set_cell(i, 2, "#{b.send("career_" + params[:stat])}")
					i += 1
				}
			end
		options = { :width => 600, :showRowNumber => true, :allowHtml =>true }
		options.each_pair do | key, value |
			@table.send "#{key}=", value
		end
	end
  
    def active
		@batting_stats = BattingStat.active_sort(params[:stat])
		@table = GoogleVisualr::Table.new
		@table.add_column('string' , 'Name')
		@table.add_column('string' , 'Bats')
		if params[:stat] == 'rbi'
			@table.add_column('string' , params[:stat].upcase)
		else @table.add_column('string' , params[:stat].titleize)
		end
		@table.add_rows(50)
		i = 0
			if BattingStat.accessible_attributes.include?(params[:stat])
				@batting_stats.each { |k, v|
					@table.set_cell(i, 0, "<a href='/players/#{k.id}'>#{k.name}</a>")
					if !k.bats.nil?
						@table.set_cell(i, 1, k.bats)
					else @table.set_cell(i, 1, 'N/A')
					end
					@table.set_cell(i, 2, "#{v}")
					i += 1
				}
			else 
				@batting_stats.each { |b|
					@table.set_cell(i, 0, "<a href='/players/#{b.id}'>#{b.name}</a>")
					if !b.bats.nil?
						@table.set_cell(i, 1, b.bats)
					else @table.set_cell(i, 1, 'N/A')
					end
					@table.set_cell(i, 2, "#{b.send("career_" + params[:stat])}")
					i += 1
				}
			end	

		options = { :width => 600, :showRowNumber => true, :allowHtml=>true }
		options.each_pair do | key, value |
			@table.send "#{key}=", value
		end
	end
	
	def season_compare
		@batters = BattingStat.season_compare(params[:comp])
		if @batters.empty?	
			flash[:notice] = "One or more of the players you have chosen do not have batting statistics available. Please select different players."
			redirect_to :back
		else
			@table = GoogleVisualr::Table.new
			@table.add_column('string' , 'Name')
			@table.add_column('string' , 'Bats')
			@table.add_column('string' , 'Year')
			@table.add_column('string' , 'Age')
			@table.add_column('string' , 'Team')
			@table.add_column('string' , 'League')
			@table.add_column('number' , 'G')
			@table.add_column('number' , 'PA')
			@table.add_column('number' , 'AB')
			@table.add_column('number' , 'R')
			@table.add_column('number' , 'H')
			@table.add_column('number' , '2B')
			@table.add_column('number' , '3B')
			@table.add_column('number' , 'HR')
			@table.add_column('number' , 'RBI')
			@table.add_column('number' , 'TB')
			@table.add_column('number' , 'SB')
			@table.add_column('number' , 'CS')
			@table.add_column('number' , 'BB')
			@table.add_column('number' , 'K')
			@table.add_column('string' , 'BA')
			@table.add_column('string' , 'OBP')
			@table.add_column('string' , 'SLG')
			@table.add_column('string' , 'OPS')
			@table.add_rows(@batters.size)
			i = 0
			@batters.each {|b|
				@table.set_cell(i, 0, "<a href='/players/#{b[0].player_id}'>#{b[0].player.name}</a>")
				if !b[0].player.bats.nil?
					@table.set_cell(i, 1, b[0].player.bats.to_s)
				else @table.set_cell(i, 1, 'N/A')
				end
				games="\"Games\""
		runs="\"Runs\""
		bats="\"At Bats\""
		plates="\"Plate Appearances\""
		hits="\"Hits\""
		doubles="\"Doubles\""
		triples="\"Triples\""
		home="\"Home Runs\""
		rbi="\"RBI\""
		stolen="\"Stolen Bases\""
		caught="\"Caught Stealing\""
		walks="\"Walks\""
		strikes="\"Strikeouts\""
		bases="\"Total Bases\""
				@table.set_cell(i, 2, b[0].team.year.to_s)
				@table.set_cell(i, 3, b[0].player.age(b[0].team.year).to_s)
				@table.set_cell(i, 4, "<a href='/teams/#{b[0].team.id}'>#{b[0].team.name}</a>")
				@table.set_cell(i, 5, b[0].team.division.league.abbrev.to_s)
				@table.set_cell(i, 6, b[0].games, "<span title=#{games}>#{b[0].games.to_s}</span>")
		@table.set_cell(i, 7, b[0].plate_appearances, "<span title=#{plates}>#{b[0].plate_appearances.to_s}</span>")
		@table.set_cell(i, 8, b[0].at_bats, "<span title=#{bats}>#{b[0].at_bats.to_s}</span>")
		@table.set_cell(i, 9, b[0].runs, "<span title=#{runs}>#{b[0].runs.to_s}</span>")
		@table.set_cell(i, 10, b[0].hits, "<span title=#{hits}>#{b[0].hits.to_s}</span>")
		@table.set_cell(i, 11, b[0].doubles, "<span title=#{doubles}>#{b[0].doubles.to_s}</span>")
		@table.set_cell(i, 12, b[0].triples, "<span title=#{triples}>#{b[0].triples.to_s}</span>")
		@table.set_cell(i, 13, b[0].home_runs, "<span title=#{home}>#{b[0].home_runs.to_s}</span>")
		@table.set_cell(i, 14, b[0].rbi, "<span title=#{rbi}>#{b[0].rbi.to_s}</span>")
		@table.set_cell(i, 15, b[0].total_bases, "<span title=#{bases}>#{b[0].total_bases.to_s}</span>")
		@table.set_cell(i, 16, b[0].stolen_bases, "<span title=#{stolen}>#{b[0].stolen_bases.to_s}</span>")
		@table.set_cell(i, 17, b[0].caught_stealing, "<span title=#{caught}>#{b[0].caught_stealing.to_s}</span>")
		@table.set_cell(i, 18, b[0].walks, "<span title=#{walks}>#{b[0].walks.to_s}</span>")
		@table.set_cell(i, 19, b[0].strikeouts, "<span title=#{strikes}>#{b[0].strikeouts.to_s}</span>")
		@table.set_cell(i, 20, "<span title='Batting Average'>#{b[0].batting_average.to_s}</span>")
		@table.set_cell(i, 21, "<span title='Slugging Percentage'>#{b[0].slugging_percentage.to_s}</span>")
		@table.set_cell(i, 22, "<span title='On Base Percentage'>#{b[0].on_base_percentage.to_s}</span>")
		@table.set_cell(i, 23, "<span title='On Base+Slugging'>#{b[0].on_base_plus_slugging.to_s}</span>")
				i += 1
			}
			
			options = { :width => '100%', :allowHtml=>true }
			options.each_pair do | key, value |
				@table.send "#{key}=", value
			end
			
				runs="\"Runs\""
		bats="\"At Bats\""
		hits="\"Hits\""
		home="\"Home Runs\""
		rbi="\"RBI\""
		stolen="\"Stolen Bases\""

			@chart = GoogleVisualr::Table.new
			@chart.add_column('string' , 'Name')
			@chart.add_column('string' , 'Bats')
			@chart.add_column('string' , 'Year')
			@chart.add_column('string' , 'Age')
			@chart.add_column('string' , 'Team')
			@chart.add_column('string' , 'League')
			@chart.add_column('number' , 'AB')
			@chart.add_column('number' , 'R')
			@chart.add_column('number' , 'H')
			@chart.add_column('number' , 'HR')
			@chart.add_column('number' , 'RBI')
			@chart.add_column('number' , 'SB')
			@chart.add_column('string' , 'BA')
			@chart.add_rows(@batters.size)
			i = 0
			@batters.each {|b|
				@chart.set_cell(i, 0, "<a href='/players/#{b[0].player_id}'>#{b[0].player.name}</a>")
				if !b[0].player.bats.nil?
					@chart.set_cell(i, 1, b[0].player.bats.to_s)
				else @chart.set_cell(i, 1, 'N/A')
				end
				@chart.set_cell(i, 2, b[0].team.year.to_s)
				@chart.set_cell(i, 3, b[0].player.age(b[0].team.year).to_s)
				@chart.set_cell(i, 4, "<a href='/teams/#{b[0].team.id}'>#{b[0].team.name}</a>")
				@chart.set_cell(i, 5, b[0].team.division.league.abbrev.to_s)
				@chart.set_cell(i, 6, b[0].at_bats, "<span title=#{bats}>#{b[0].at_bats.to_s}</span>")
				@chart.set_cell(i, 7, b[0].runs, "<span title=#{runs}>#{b[0].runs.to_s}</span>")
				@chart.set_cell(i, 8, b[0].hits, "<span title=#{hits}>#{b[0].hits.to_s}</span>")
				@chart.set_cell(i, 9, b[0].home_runs, "<span title=#{home}>#{b[0].home_runs.to_s}</span>")
				@chart.set_cell(i, 10, b[0].rbi, "<span title=#{rbi}>#{b[0].rbi.to_s}</span>")
				@chart.set_cell(i, 11, b[0].stolen_bases, "<span title=#{stolen}>#{b[0].stolen_bases.to_s}</span>")
				@chart.set_cell(i, 12, "<span title='Batting Average'>#{b[0].batting_average.to_s}</span>")
				i += 1
			}
			
			options = { :width => '100%', :allowHtml=>true }
			options.each_pair do | key, value |
				@chart.send "#{key}=", value
			end
		end
	end
	
	def career_compare
		@batters = BattingStat.career_compare(params[:comp])
		if @batters.empty?	
			flash[:notice] = "One or more of the players you have chosen do not have batting statistics available. Please select different players."
			redirect_to :back
		else
			@player = []
			@players = []
			@batters.each_value {|value|
				if @player.include?(value)
				else @player.push(value)
				end
			}
			@max = []
			@player.each {|p|
				@players.push(Player.find(p.to_i))

StatTracker/app/helpers/batting_stats_helper.rb
module BattingStatsHelper
end

StatTracker/app/views/batting_stats/_chart.html.erb
<table class = 'chart'>
	<tr>
		<td class = 'chart'>
			<div id = 'chart1'></div>
			<%= raw @chart.render('chart1') %>
		</td>
		<td class = 'chart'>
			<div id = 'chart2'></div>
			<%= raw @chart2.render('chart2') %>
		</td>
	</tr>
</table>

StatTracker/app/views/batting_stats/career_compare.html.erb
<% title "Career Batting Comparison" %>

	<div id = 'table_place'>
		<%= render :partial => 'table'  %> 
	</div>

	<br/>
	
	<div id = "table_checkbox">
		<span><p>Check which statistics you want to view in the table</p></span>
		<%= form_tag change_career_table_batting_path(:players => @players), :remote => true, :id => "change_table" do %>
			<span title="Games"><%= check_box_tag 'stat[]', 'games', false %>G</span>&nbsp;
			<span title="Plate Appearances"><%= check_box_tag 'stat[]', 'plate_appearances', false %>PA</span>&nbsp;
			<span title="At Bats"><%= check_box_tag 'stat[]', 'at_bats', false %>AB</span>&nbsp;
			<span title="Runs"><%= check_box_tag 'stat[]', 'runs', true %>R</span>&nbsp;
			<span title="Hits"><%= check_box_tag 'stat[]', 'hits', true %>H</span>&nbsp;
			<span title="Doubles"><%= check_box_tag 'stat[]', 'doubles', false %>2B</span>&nbsp;
			<span title="Triples"><%= check_box_tag 'stat[]', 'triples', false %>3B</span>&nbsp;
			<span title="Home Runs"><%= check_box_tag 'stat[]', 'home_runs', true %>HR</span>&nbsp;
			<span title="Total Bases"><%= check_box_tag 'stat[]', 'total_bases', false %>TB</span>&nbsp;
			<span title="Extra Base Hits"><%= check_box_tag 'stat[]', 'extra_base_hits', false %>XBH</span>&nbsp;
			<br/>
			<span title="RBI"><%= check_box_tag 'stat[]', 'rbi', true %>RBI</span>&nbsp;
			<span title="Stolen Bases"><%= check_box_tag 'stat[]', 'stolen_bases', true %>SB</span>&nbsp;
			<span title="Caught Stealing"><%= check_box_tag 'stat[]', 'caught_stealing', false %>CS</span>&nbsp;
			<span title="Walks"><%= check_box_tag 'stat[]', 'walks', false %>BB</span>&nbsp;
			<span title="Strikeouts"><%= check_box_tag 'stat[]', 'strikeouts', false %>K</span>&nbsp;
			<span title="Intentional Walks"><%= check_box_tag 'stat[]', 'intentional_walks', false %>IBB</span>&nbsp;
			<span title="Hit by Pitch"><%= check_box_tag 'stat[]', 'hit_by_pitch', false %>HBP</span>&nbsp;
			<span title="Sacrifice Hits"><%= check_box_tag 'stat[]', 'sacrifice_hits', false %>SAC</span>&nbsp;
			<span title="Sacrifice Flies"><%= check_box_tag 'stat[]', 'sacrifice_flies', false %>SF</span>&nbsp;
			<span title="Grounded into Double Plays"><%= check_box_tag 'stat[]', 'grounded_into_double_plays', false %>GIDP</span>&nbsp;
			<br/>
			<%= submit_tag 'Update' %>
		<% end %>
	</div>
	
	<br/>
	<br/>
	
	<div id = 'chart_select'>
		<span><p>Select a new statistic to change the charts</p></span>
		<%= form_tag change_career_chart_batting_path(:players => @players), :id => "change_chart", :remote => true do %>
			<%= select_tag "chart_type", 
			raw("<option>Home Runs</option>
			<option>Games</option>
			<option>Plate Appearances</option>
			<option>At Bats</option>
			<option>Runs</option>
			<option>Hits</option>
			<option>Doubles</option>
			<option>Triples</option>
			<option>Total Bases</option>
			<option>Extra Base Hits</option>
			<option>RBI</option>
			<option>Stolen Bases</option>
			<option>Caught Stealing</option>
			<option>Walks</option>
			<option>Strikeouts</option>
			<option>Intentional Walks</option>
			<option>Hit by Pitch</option>
			<option>Sacrifice Hits</option>
			<option>Sacrifice Flies</option>
			<option>Grounded into Double Plays</option>")
			%>
			<%#= submit_tag 'Update' %>
		<% end %>
	</div>
	<br/>
	
	<div id = 'chart_place'>
		<%= render :partial => 'chart'  %> 
	</div>
	
	<script type="text/javascript">
          $('#chart_type').change(function(){
            $(this).parents('form:first').submit();
          });
        </script>

StatTracker/app/views/batting_stats/index.html.erb
<% title "Batting Stats" %>

<table>
  <tr>
    <th>Player</th>
    <th>Team</th>
	<th>Year</th>
	<th>Doubles</th>
	<th>Triples</th>
	<th>Home Runs</th>
    <th>Runs Batted In</th>

  </tr>
  <% for batting_stat in @batting_stats %>
    <tr>
      <td><%= batting_stat.player.last_name %></td>
      <td><%= batting_stat.team.name %></td>
	  <td><%= batting_stat.team.year %></td>
	  <td><%= batting_stat.doubles%></td>
	  <td><%= batting_stat.triples %></td>
      <td><%= batting_stat.home_runs %></td>
	  <td><%= batting_stat.rbi %></td>
    </tr>
  <% end %>
</table>
<p><%= link_to "New Batting Stat", new_batting_stat_path(batting_stat) %></p>

StatTracker/app/views/batting_stats/multi_compare.html.erb
<% title "Multi-Season Batting Comparison" %>

You are comparing <%= @strings.join(", ") %>
<br/>
<br/>

	<div id = 'table_place'>
		<%= render :partial => 'table'  %> 
	</div>

	<br/>
	
	<div id = "table_checkbox">
		<span><p>Check which statistics you want to view in the table</p></span>
		<%= form_tag change_multi_table_batting_path(:players => @players, :batters => @batters.keys), :remote => true, :id => "change_table" do %>
			<span title="Games"><%= check_box_tag 'stat[]', 'games', false %>G</span>&nbsp;
			<span title="Plate Appearances"><%= check_box_tag 'stat[]', 'plate_appearances', false %>PA</span>&nbsp;
			<span title="At Bats"><%= check_box_tag 'stat[]', 'at_bats', false %>AB</span>&nbsp;
			<span title="Runs"><%= check_box_tag 'stat[]', 'runs', true %>R</span>&nbsp;
			<span title="Hits"><%= check_box_tag 'stat[]', 'hits', true %>H</span>&nbsp;
			<span title="Doubles"><%= check_box_tag 'stat[]', 'doubles', false %>2B</span>&nbsp;
			<span title="Triples"><%= check_box_tag 'stat[]', 'triples', false %>3B</span>&nbsp;
			<span title="Home Runs"><%= check_box_tag 'stat[]', 'home_runs', true %>HR</span>&nbsp;
			<span title="Total Bases"><%= check_box_tag 'stat[]', 'total_bases', false %>TB</span>&nbsp;
			<span title="Extra Base Hits"><%= check_box_tag 'stat[]', 'extra_base_hits', false %>XBH</span>&nbsp;
			<br/>
			<span title="RBI"><%= check_box_tag 'stat[]', 'rbi', true %>RBI</span>&nbsp;
			<span title="Stolen Bases"><%= check_box_tag 'stat[]', 'stolen_bases', true %>SB</span>&nbsp;
			<span title="Caught Stealing"><%= check_box_tag 'stat[]', 'caught_stealing', false %>CS</span>&nbsp;
			<span title="Walks"><%= check_box_tag 'stat[]', 'walks', false %>BB</span>&nbsp;
			<span title="Strikeouts"><%= check_box_tag 'stat[]', 'strikeouts', false %>K</span>&nbsp;
			<span title="Intentional Walks"><%= check_box_tag 'stat[]', 'intentional_walks', false %>IBB</span>&nbsp;
			<span title="Hit by Pitch"><%= check_box_tag 'stat[]', 'hit_by_pitch', false %>HBP</span>&nbsp;
			<span title="Sacrifice Hits"><%= check_box_tag 'stat[]', 'sacrifice_hits', false %>SAC</span>&nbsp;
			<span title="Sacrifice Flies"><%= check_box_tag 'stat[]', 'sacrifice_flies', false %>SF</span>&nbsp;
			<span title="Grounded into Double Plays"><%= check_box_tag 'stat[]', 'grounded_into_double_plays', false %>GIDP</span>&nbsp;
			<br/>
			<%= submit_tag 'Update' %>
		<% end %>
	</div>
	
	<br/>
	<br/>
	
	<div id = 'chart_select'>
		<span><p>Select a new statistic to change the charts</p></span>
		<%= form_tag change_multi_chart_batting_path(:players => @players, :batters => @batters.keys, :max => @max, :years => @years), :id => "change_chart", :remote => true do %>
			<%= select_tag "chart_type", 
			raw("<option>Home Runs</option>
			<option>Games</option>
			<option>Plate Appearances</option>
			<option>At Bats</option>
			<option>Runs</option>
			<option>Hits</option>
			<option>Doubles</option>
			<option>Triples</option>
			<option>Total Bases</option>
			<option>Extra Base Hits</option>
			<option>RBI</option>
			<option>Stolen Bases</option>
			<option>Caught Stealing</option>
			<option>Walks</option>
			<option>Strikeouts</option>
			<option>Intentional Walks</option>
			<option>Hit By Pitch</option>
			<option>Sacrifice Hits</option>
			<option>Sacrifice Flies</option>
			<option>Grounded Into Double Plays</option>")
			%>
			<%#= submit_tag 'Update' %>
		<% end %>
	</div>
	<br/>
	
	<div id = 'chart_place'>
		<%= render :partial => 'chart'  %> 
	</div>

        <script type="text/javascript">
          $('#chart_type').change(function(){
            $(this).parents('form:first').submit();
          });
        </script>
	
	